# Generated by Django 4.0.3 on 2022-03-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='new',
            old_name='text',
            new_name='new_text',
        ),
    ]
