# Generated by Django 4.0.3 on 2022-03-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_new_options_rename_text_new_new_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='new_text',
            new_name='text',
        ),
    ]
