# Generated by Django 4.0.3 on 2022-03-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_new_text_new_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='text',
            new_name='new_text',
        ),
    ]
